### ISSUE TITLE
Change filterEthList function name to processEthList

### ISSUE THREAD

**Issue by wildmolasses** [geleeroyale/donation-leaderboard#14]
Hey! I was thinking we could change `filterEthList()` to `processEthList()`. After all, there are a few steps we'll have to take:

1. Filter out transactions with value of 0.
2. Find sum of each address's transactions.
3. Rank and sort address list.

This could all occur within one function (perhaps with smaller functional parts) and so I was thinking we could call it `processEthList()`.

**Comment by geleeroyale** [comment]
Of course! You are right about the extended functionality =)
