### ISSUE TITLE
Style leaderboard table

### ISSUE THREAD

**Issue by wildmolasses** [geleeroyale/donation-leaderboard#16]
I just made the leaderboard into an HTML table per #5. It looks pretty bad though :) I figure it should be styled appropriately. I noticed some table style classes in `App.css`. Did you write these classes with this task in mind, @geleeroyale?

**Comment by geleeroyale** [comment]
Actually the barebones project is a fork from a tutorial (road to react) as I am only learning REACT myself at the moment. Any css except the classes in the end of App.css are from road-to-react. I happily accept any changes :-)
