### ISSUE TITLE
gas oracle broken

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#24]
gas oracle is not working anymore

**Comment by GriffGreen** [comment]
yeah i would just set the gas to 60k and call it good

**Comment by sponnet** [comment]
The gas depends on the length of the remark - so it is variable. I assume @geleeroyale is talking about the gasprice oracle.
Provide an alternative oracle is on my bucket list somewhere. Shouldn't we apply for funding from the Ethereum Foundation for all of this ?

**Comment by GriffGreen** [comment]
But it is a lot easier to make a character limit in the UI and a set gas limit then it is to create a gas oracle...

**Comment by geleeroyale** [comment]
gasprice calculation seems to be working fine for main net
