### ISSUE TITLE
group transactions by address and sum their value

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#3]

**Comment by wildmolasses** [comment]
Hi @geleeroyale, I have the functionality complete on this, but it brings a few other questions to mind. Specifically, after we sum the transactions, it seems like our table should display 1 row per address, with summed donation value. However, now we will not have 1 transaction link, but a few. Then, should our "tx link" field have multiple tx links? E.g. See transaction [1] [2] [3]

**Comment by geleeroyale** [comment]
Interesting point - you are right, I haven't thought about this. Well there is no right way to do this, so I would suggest skipping the address links for now. 

We can substitute with a link to donation address that displays all transactions.

I don't think its a bad idea to show all transactions by one address as a later step - maybe with full links as a popup?
