### ISSUE TITLE
Deploy and announce ScalingNOW donation leaderboard

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#31]

**Comment by wildmolasses** [comment]
Hey @geleeroyale where is it announced? Would love to see it in production :)

**Comment by geleeroyale** [comment]
https://scalingnow.giveth.io :-D ... I love it ... thank you so much for your contributions @emazurek! @sponnet lifted the heavy stuff in the end and I made it a little prettier. Hope it evolves further. Go donation leaderboard! 😅
