### ISSUE TITLE
implement web3(MetaMask) function for making a transaction

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#8]

**Comment by wildmolasses** [comment]
Does this suggest a "donate" button is necessary?

**Comment by geleeroyale** [comment]
Yes - I would say this warrants at least a button. It might be wise to have two forms (address and input - see issue #9 ) and a button even.

**Comment by sponnet** [comment]
I'm on this. https://github.com/sponnet/eth-leaderboard/tree/%238_function_for_making_a_transaction
