### ISSUE TITLE
implement web3(MetaMask) function for signing a string to an address

### ISSUE THREAD

**Issue by geleeroyale** [geleeroyale/donation-leaderboard#9]

**Comment by wildmolasses** [comment]
Hi @geleeroyale, could you give some more detail on this issue? Thanks!

**Comment by geleeroyale** [comment]
We want people to be able to put a name to their address-

This functionality can be observed on the original github.com/merrymerkle/merrymerkle.github.io - you should take a look at the /js/main.js to see how the mm team did it. Basically this functionality lets you put in a string that gets converted to hex and opens a new transaction. The converted string is written to ```input``` and sent with the transaction. Once the tx is complete, we can read the ```input``` value and convert it back to a string to display on the leaderboard - this string should replace the address in address field then.

**Comment by sponnet** [comment]
I already added web3 for the number comparison using BigNumber and for formatting the balances.
I don't have a rinkeby node URL , so currently it only will work when metamask is used. If the user doesn't have metamask installed, it will try localhost to connect to a node..
Do you have a rinkeby node running that we can use for that ? If so I can add its URL to the web3 constructor.

**Comment by sponnet** [comment]
I'm on this : https://github.com/sponnet/eth-leaderboard/tree/%238_function_for_making_a_transaction

**Comment by geleeroyale** [comment]
Although sponnet already included this functionality - it has been broken with this pull request:

https://github.com/geleeroyale/eth-leaderboard/pull/22

**Comment by wildmolasses** [comment]
Gotcha @geleeroyale: right now, it should be taking the 1st 'remark' of each group; would we prefer the last?

Per your comment on PR #22:

> Please note that adding the sum broke display of 'remark' - this field should display a message with the 'input' value set. This should display the last valid 'input' and ignore all subsequent empty 'input' values.

Are you suggesting a flow such as the following:
1. see if first tx has 'remark' -- if so, use this and ignore the rest
2. if first tx has no remark, see if second tx has 'remark' -- if so, use this and ignore the rest
3. etc

**Comment by geleeroyale** [comment]
Flow:

1 - ignore all standard input (should be 0x) 
2 - display the first 'remark' found
3 - go through later transactions
3 - if there is a newer 'remark' found use that for display

**Comment by wildmolasses** [comment]
Thanks @geleeroyale, #23 should handle it.

**Comment by geleeroyale** [comment]
It does! Nice!
